feat(hold): Track aircraft in hold proximity
VATSIM-UK/uk-controller-api pull request #810
Opened 2022-01-28 18:07 UTC by AndyTWF

Relates to https://github.com/VATSIM-UK/uk-controller-plugin/issues/416

2022-02-02 20:32 UTC, AxonC requested changes

2022-02-02 20:32 UTC, AxonC commented on app/Services/HoldService.php
> +                        ) > 22224
I think this is a magic number?

2022-02-02 20:36 UTC, AndyTWF commented on app/Services/HoldService.php
> +                        ) > 22224
It's 12nm, added a const!

2022-02-04 15:54 UTC, AxonC approved these changes

2022-02-19 10:12 UTC, merged

2022-02-19 10:16 UTC, VATSIMUK commented
:tada: This PR is included in version 6.1.0 :tada:

The release is available on [GitHub release](https://github.com/VATSIM-UK/uk-controller-api/releases/tag/6.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: